#!/usr/bin/env perl
#
#       manifest.pl
#
#       Copyright 2010-2011 Frédéric Galusik <fredg~at~salixos~dot~org>
#       License: BSD Revised
#
###############################################################################

use strict;
use warnings;
use IO::Compress::Bzip2 qw(bzip2 $Bzip2Error);

my $VERSION = 0.1;

my @dirslist = qw( a ap d f games gnome kde l locale lxde n x xap xfce );
my $dir;
my @pkglist;
my @pkgs;
my $pkg;
my $pathpkg;
my $manifest = ".MANIFEST";
my $manifbz = "MANIFEST.bz2";
my $manifbak = "MANIFEST.bz2.old";

# backup
if ( -e $manifbz ) {
        rename $manifbz,$manifbak;
        }

# list ./dir/pkgs
foreach $dir (@dirslist) {
    opendir(DIR, "./$dir") or die "Cannot open './$dir' : $!\n";
    @pkgs = grep /\.txz$/, readdir(DIR);
    @pkgs = sort @pkgs;
        foreach $pkg (@pkgs) {
            $pathpkg = "./$dir/$pkg";
            push(@pkglist, $pathpkg);
        }
    closedir(DIR);
}

# write MANIFEST
open(F, ">>$manifest");
foreach $pathpkg (@pkglist) {
    print F "++========================================\n";
    print F "||\n";
    print F "||   Package:  ", $pathpkg, "\n";
    print F "||\n";
    print F "++========================================\n";
    system ("tar -Jtvf $pathpkg >> $manifest");
    print F "\n\n";
}
close(F);

# bzip2
bzip2 $manifest => "$manifbz" or die "bzip2 failed: $Bzip2Error\n";
unlink("$manifest");
