#!/usr/bin/env perl
#
#       manifest.pl
#
#       Copyright 2010-2011 Frédéric Galusik <fredg~at~salixos~dot~org>
#       License: BSD Revised
#
###############################################################################

use strict;
use warnings;
use File::stat;
use IO::Compress::Bzip2 qw(bzip2 $Bzip2Error);

my @dirslist = qw( a ap d f games gnome kde l locale lxde n x xap xfce );
my $dir;
my @pkglist;
my @pkgs;
my $pkg;
my $pathpkg;
my $manifest = ".MANIFEST";
my $manifbz = "MANIFEST.bz2";
my $manifbak = ".MANIFEST.bz2.old";
my $packagestxt = "../PACKAGES.TXT";
my $a = stat($packagestxt);
my $b = stat($manifbz);

# check if it is needed to run this script
sub check {
    if ( $a->mtime < $b->mtime ) {
        die "No new or updated packages, MANIFEST aborting ...\n";
        } else {
            print "MANIFEST update necessary, processing ...\n";
            rename $manifbz,$manifbak;
            }
}

# check PACKAGES.TXT & MANIFEST.bz2
if ( -e $manifbz and -e $packagestxt ) {
    check()
    } else {
        print "MANIFEST processing ...\n";
    }

# list ./dir/pkgs
foreach $dir (@dirslist) {
    opendir(DIR, "./$dir") or die "Cannot open './$dir' : $!\n";
    @pkgs = grep /\.t[bgx]z$/, readdir(DIR);
        foreach $pkg (@pkgs) {
            $pathpkg = "./$dir/$pkg";
            push(@pkglist, $pathpkg);
        }
    closedir(DIR);
}

# write MANIFEST
open(F, ">>$manifest");
foreach $pathpkg (@pkglist) {
    print F "++========================================\n";
    print F "||\n";
    print F "||   Package:  ", $pathpkg, "\n";
    print F "||\n";
    print F "++========================================\n";
    system ("tar -tvf $pathpkg >> $manifest");
    print F "\n\n";
}
close(F);

# bzip2
bzip2 $manifest => "$manifbz" or die "bzip2 failed: $Bzip2Error\n";
unlink("$manifest");

